### ISSUE TITLE
Nexus testing

### ISSUE THREAD

**Issue by ahmad11111111111** [ahmad11111111111/Brain-Controller-App#8]
**Objective**
Testing the Synchronized data collection app with the nexus device.
**Actions**
-Testing the application inside of Nexus
- Testing the application while a game is running
- Testing the device With the subject To make sure everything is working how it should

**Comment by ahmad11111111111** [comment]
getting the libbci system to work

**Comment by kevincar** [comment]
Was notified that you assigned me to this. Is there something in particular you'd like me to check out?

**Comment by ahmad11111111111** [comment]
hey kevin i ran pytest on the libbci system and it gave this error:

``` ======================================== short test summary info ========================================
ERROR test_inputdevicemanager.py::TestInputDeviceManager::test__n_module_nodes - FileNotFoundError: [Errno 2] No such file or directory: 'tests/indevice.py'
ERROR test_inputdevicemanager.py::TestInputDeviceManager::test__collect_modules_from_folder - FileNotFoundError: [Errno 2] No such file or directory: 'tests/indevice.py'
ERROR test_inputdevicemanager.py::TestInputDeviceManager::test__collect_modules_from_files - FileNotFoundError: [Errno 2] No such file or directory: 'tests/indevice.py'
ERROR test_inputdevicemanager.py::TestInputDeviceManager::test_inputdevicemanager - FileNotFoundError: [Errno 2] No such file or directory: 'tests/indevice.py'
ERROR test_inputdevicemanager.py::TestInputDeviceManager::test_store_selection - FileNotFoundError: [Errno 2] No such file or directory: 'tests/indevice.py'
=========================================== 5 errors in 0.10s =========================================== ```


i have the joystick class stored here 

/home/ahmad/lab/libbci/deviceapis/inputdevices

**Comment by ahmad11111111111** [comment]
I just posted something

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Thursday, October 12, 2023 11:29:54 AM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] Nexus testing (Issue #8)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Was notified that you assigned me to this. Is there something in particular you'd like me to check out?

**Comment by kevincar** [comment]
the `libbci` repository is the library. It doesn't actually get the system running. That is the main `bci` repository. Place your `deviccapis` folder in the cloned `bci` repo

**Comment by ahmad11111111111** [comment]
kevin have you looked at the output. I want to make sure I'm storing the joystick properly

**Comment by kevincar** [comment]
The output of what? The joystick file? Where can I see it?

**Comment by ahmad11111111111** [comment]
Ok now im calling inputdevicemanager.dectect devices and its printing [].

I have the device apis folder saved here 

/home/ahmad/lab/libbci/deviceapis

**Comment by ahmad11111111111** [comment]
i see

**Comment by ahmad11111111111** [comment]
ok so i see the bci folder and the device api folder, so now where do i store the bci repo?

**Comment by kevincar** [comment]
Basically if I was going to start from scratch. All you have to do is this

```
# Clone the BCI repo
git clone https://github.com/umnil/bci
cd bci

# Navigate to the input devices
cd deviceapis/inputdevice

# clone in your device repo
git clone <url-to-joystick-stuff>

# Navigate back to the BCI root folder and run the BCI system
cd ../../
python -m bci -v DEBUG
```

**Comment by ahmad11111111111** [comment]
```
(base) ➜  bci git:(main) ✗ python -m bci -v DEBUG
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ahmad/lab/bci/bci/__main__.py", line 7, in <module>
    from .application import Application
  File "/home/ahmad/lab/bci/bci/application.py", line 11, in <module>
    from .ble import Value, ValuePermissions  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/lab/bci/bci/ble/__init__.py", line 1, in <module>
    from . import charcontroller
  File "/home/ahmad/lab/bci/bci/ble/charcontroller.py", line 9, in <module>
    from bless import BlessServer, BlessGATTCharacteristic  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'bless'
(base) ➜  bci git:(main) ✗ 
```

**Comment by ahmad11111111111** [comment]
its running this error ModuleNotFoundError: No module named 'blestream'

**Comment by kevincar** [comment]
You need to install bless. There is a requirements file you can use to download all bci dependencies

**Comment by ahmad11111111111** [comment]
ive installed bless

**Comment by kevincar** [comment]
> its running this error ModuleNotFoundError: No module named 'blestream'

You need to install blestream. I believe this is also in the requirements file

**Comment by ahmad11111111111** [comment]
ok . gotit. 

now its running this 

  File "/home/ahmad/lab/bci/deviceapis/inputdevices/Brain-Controller-App/controllerinput/joystick.py", line 8, in <module>
    class Joystick(InputDevice):
                   ^^^^^^^^^^^
NameError: name 'InputDevice' is not defined

**Comment by kevincar** [comment]
You need to define `InputDevice` by importing it from libbci. Check out the device-nexus classes for an example

**Comment by ahmad11111111111** [comment]
i think it ran with no issues

**Comment by kevincar** [comment]
Excellent! I would next create a plot with 2 subfigures, one of the joy stick data, the other of the neural data so that we can ensure that the data is synched.

**Comment by ahmad11111111111** [comment]
So, I just call get input with libbci?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Thursday, October 12, 2023 7:01:17 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] Nexus testing (Issue #8)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Excellent! I would next create a plot with 2 subfigures, one of the joy stick data, the other of the neural data so that we can ensure that the data is synched.

**Comment by kevincar** [comment]
> So, I just call get input with libbci?

Are you running into errors? What's the issue you're referring to with this question?

**Comment by ahmad11111111111** [comment]
i ran python -m bci -v DEBUG 

but i dont realy know how to use the bci library.

I have libbci pip installed but i cant pip install bci

**Comment by kevincar** [comment]
`python -m bci -v DEBUG` should run for ever until you type `ctrl+C` to shut it down. You should see the decoded output printed to the screen. During this time, data should be written to files because each device's `get_input` method will be called repeatedly.

So just run the `bci` app for a while then shut it down and check the resulting output files

**Comment by ahmad11111111111** [comment]
it did not run forever

**Comment by ahmad11111111111** [comment]
heres the full output

``` (env1) ➜  bci git:(main) ✗ python -m bci -v DEBUG
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:bci.application:Application entry point
DEBUG:bci.devices.devicemanager:Potential Modules: ['deviceapis.inputdevices.testdevice', 'deviceapis.inputdevices.neurosity', 'deviceapis.inputdevices.keyboard', 'deviceapis.inputdevices.Brain-Controller-App', 'deviceapis.inputdevices.nexus', 'deviceapis.inputdevices.__pycache__', 'deviceapis.inputdevices.Brain-Controller-App.controllerinput', 'deviceapis.inputdevices.Brain-Controller-App.notebooks']
pygame 2.5.1 (SDL 2.28.2, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.testdevice' from '/home/ahmad/lab/bci/deviceapis/inputdevices/testdevice.py'>
DEBUG:bci.devices.devicemanager:Trying class: TestInputDevice
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.neurosity' (<_frozen_importlib_external.NamespaceLoader object at 0x7fbe39d44390>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.keyboard' (<_frozen_importlib_external.NamespaceLoader object at 0x7fbe3c7ba250>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.Brain-Controller-App' (<_frozen_importlib_external.NamespaceLoader object at 0x7fbe399e7990>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.nexus' (<_frozen_importlib_external.NamespaceLoader object at 0x7fbe3c7ba710>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.__pycache__' (<_frozen_importlib_external.NamespaceLoader object at 0x7fbe3c7ba950>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.Brain-Controller-App.controllerinput' from '/home/ahmad/lab/bci/deviceapis/inputdevices/Brain-Controller-App/controllerinput/__init__.py'>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.Brain-Controller-App.notebooks' (<_frozen_importlib_external.NamespaceLoader object at 0x7fbe3c7ba7d0>)>
DEBUG:bci.devices.devicemanager:Potential Modules: ['deviceapis.outputdevices.testdevice', 'deviceapis.outputdevices.__pycache__', 'deviceapis.outputdevices.neomano']
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.outputdevices.testdevice' from '/home/ahmad/lab/bci/deviceapis/outputdevices/testdevice.py'>
DEBUG:bci.devices.devicemanager:Trying class: TestOutputDevice
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.outputdevices.__pycache__' (<_frozen_importlib_external.NamespaceLoader object at 0x7fbdff70e210>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.outputdevices.neomano' (<_frozen_importlib_external.NamespaceLoader object at 0x7fbdfd56f350>)>
INFO:bci.devices.devicemanager:Devices: [<deviceapis.inputdevices.testdevice.TestInputDevice object at 0x7fbdff76f210>]
INFO:bci.devices.devicemanager:Devices: [<deviceapis.outputdevices.testdevice.TestOutputDevice object at 0x7fbdff750610>]
DEBUG:bci.application:Loading display server
DEBUG:bci.display_server:Adding our primary service
{'message': 'Task exception was never retrieved', 'exception': InvalidObjectPathError('invalid object path: /org/bluez/BCI-Application/service0001'), 'future': <Task finished name='Task-2' coro=<DisplayServer.start() done, defined at /home/ahmad/lab/bci/bci/display_server.py:66> exception=InvalidObjectPathError('invalid object path: /org/bluez/BCI-Application/service0001')>}
ERROR:bci.application:Caught exception: invalid object path: /org/bluez/BCI-Application/service0001
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ahmad/lab/bci/bci/__main__.py", line 53, in <module>
    main(**args)
  File "/home/ahmad/lab/bci/bci/__main__.py", line 14, in main
    app.start()
  File "/home/ahmad/lab/bci/bci/application.py", line 94, in start
    cur_loop.run_until_complete(self.loop_entry_point())
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ahmad/lab/bci/bci/application.py", line 102, in loop_entry_point
    await self.display_server.start_concurrent()
  File "/home/ahmad/lab/bci/bci/display_server.py", line 101, in start_concurrent
    await self.services_loaded_event.wait()
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError
(env1) ➜  bci git:(main) ✗ python -m bci -v DEBUG
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:bci.application:Application entry point
DEBUG:bci.devices.devicemanager:Potential Modules: ['deviceapis.inputdevices.testdevice', 'deviceapis.inputdevices.neurosity', 'deviceapis.inputdevices.keyboard', 'deviceapis.inputdevices.Brain-Controller-App', 'deviceapis.inputdevices.nexus', 'deviceapis.inputdevices.__pycache__', 'deviceapis.inputdevices.Brain-Controller-App.controllerinput', 'deviceapis.inputdevices.Brain-Controller-App.notebooks']
pygame 2.5.1 (SDL 2.28.2, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.testdevice' from '/home/ahmad/lab/bci/deviceapis/inputdevices/testdevice.py'>
DEBUG:bci.devices.devicemanager:Trying class: TestInputDevice
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.neurosity' (<_frozen_importlib_external.NamespaceLoader object at 0x7fd870f89350>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.keyboard' (<_frozen_importlib_external.NamespaceLoader object at 0x7fd87184a5d0>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.Brain-Controller-App' (<_frozen_importlib_external.NamespaceLoader object at 0x7fd87184a510>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.nexus' (<_frozen_importlib_external.NamespaceLoader object at 0x7fd87184bad0>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.__pycache__' (<_frozen_importlib_external.NamespaceLoader object at 0x7fd86e9bacd0>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.Brain-Controller-App.controllerinput' from '/home/ahmad/lab/bci/deviceapis/inputdevices/Brain-Controller-App/controllerinput/__init__.py'>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.inputdevices.Brain-Controller-App.notebooks' (<_frozen_importlib_external.NamespaceLoader object at 0x7fd87184abd0>)>
DEBUG:bci.devices.devicemanager:Potential Modules: ['deviceapis.outputdevices.testdevice', 'deviceapis.outputdevices.__pycache__', 'deviceapis.outputdevices.neomano']
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.outputdevices.testdevice' from '/home/ahmad/lab/bci/deviceapis/outputdevices/testdevice.py'>
DEBUG:bci.devices.devicemanager:Trying class: TestOutputDevice
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.outputdevices.__pycache__' (<_frozen_importlib_external.NamespaceLoader object at 0x7fd834763190>)>
DEBUG:bci.devices.devicemanager:Loading module: <module 'deviceapis.outputdevices.neomano' (<_frozen_importlib_external.NamespaceLoader object at 0x7fd8325774d0>)>
INFO:bci.devices.devicemanager:Devices: [<deviceapis.inputdevices.testdevice.TestInputDevice object at 0x7fd86e9b8b50>]
INFO:bci.devices.devicemanager:Devices: [<deviceapis.outputdevices.testdevice.TestOutputDevice object at 0x7fd872be8910>]
DEBUG:bci.application:Loading display server
DEBUG:bci.display_server:Adding our primary service
{'message': 'Task exception was never retrieved', 'exception': InvalidObjectPathError('invalid object path: /org/bluez/BCI-Application/service0001'), 'future': <Task finished name='Task-2' coro=<DisplayServer.start() done, defined at /home/ahmad/lab/bci/bci/display_server.py:66> exception=InvalidObjectPathError('invalid object path: /org/bluez/BCI-Application/service0001')>}
ERROR:bci.application:Caught exception: invalid object path: /org/bluez/BCI-Application/service0001
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ahmad/lab/bci/bci/__main__.py", line 53, in <module>
    main(**args)
  File "/home/ahmad/lab/bci/bci/__main__.py", line 14, in main
    app.start()
  File "/home/ahmad/lab/bci/bci/application.py", line 94, in start
    cur_loop.run_until_complete(self.loop_entry_point())
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ahmad/lab/bci/bci/application.py", line 102, in loop_entry_point
    await self.display_server.start_concurrent()
  File "/home/ahmad/lab/bci/bci/display_server.py", line 101, in start_concurrent
    await self.services_loaded_event.wait()
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError
```

**Comment by kevincar** [comment]
Looks like you might have a Bluetooth problem. Can you see if the example script provided on the bless repository runs for you?

**Comment by ahmad11111111111** [comment]
Yeah the Bluetooth on my pc is a little touch and go. I'll see what I can do

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Thursday, October 12, 2023 7:41:40 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] Nexus testing (Issue #8)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Looks like you might have a Bluetooth problem. Can you see if the example script provided on the bless repository runs for you?

**Comment by kevincar** [comment]
Keep me posted

**Comment by ahmad11111111111** [comment]
heres the error for the bless example 

``` 
"""
Example for a BLE 4.0 Server
"""

import logging
import asyncio
import threading

from typing import Any

from bless import (  # type: ignore
        BlessServer,
        BlessGATTCharacteristic,
        GATTCharacteristicProperties,
        GATTAttributePermissions
        )

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(name=__name__)
trigger: threading.Event = threading.Event()


def read_request(
        characteristic: BlessGATTCharacteristic,
        **kwargs
        ) -> bytearray:
    logger.debug(f"Reading {characteristic.value}")
    return characteristic.value


def write_request(
        characteristic: BlessGATTCharacteristic,
        value: Any,
        **kwargs
        ):
    characteristic.value = value
    logger.debug(f"Char value set to {characteristic.value}")
    if characteristic.value == b'\x0f':
        logger.debug("NICE")
        trigger.set()


async def run(loop):
    trigger.clear()
    # Instantiate the server
    my_service_name = "Test Service"
    server = BlessServer(name=my_service_name, loop=loop)
    server.read_request_func = read_request
    server.write_request_func = write_request

    # Add Service
    my_service_uuid = "A07498CA-AD5B-474E-940D-16F1FBE7E8CD"
    await server.add_new_service(my_service_uuid)

    # Add a Characteristic to the service
    my_char_uuid = "51FF12BB-3ED8-46E5-B4F9-D64E2FEC021B"
    char_flags = (
            GATTCharacteristicProperties.read |
            GATTCharacteristicProperties.write |
            GATTCharacteristicProperties.indicate
            )
    permissions = (
            GATTAttributePermissions.readable |
            GATTAttributePermissions.writeable
            )
    await server.add_new_characteristic(
            my_service_uuid,
            my_char_uuid,
            char_flags,
            None,
            permissions)

    logger.debug(
            server.get_characteristic(
                my_char_uuid
                )
            )
    await server.start()
    logger.debug("Advertising")
    logger.info(f"Write '0xF' to the advertised characteristic: {my_char_uuid}")
    trigger.wait()
    await asyncio.sleep(2)
    logger.debug("Updating")
    server.get_characteristic(my_char_uuid)
    server.update_value(
            my_service_uuid, "51FF12BB-3ED8-46E5-B4F9-D64E2FEC021B"
            )
    await asyncio.sleep(5)
    await server.stop()

loop = asyncio.get_event_loop()
loop.run_until_complete(run(loop))
```

**Comment by ahmad11111111111** [comment]
```
RuntimeError                              Traceback (most recent call last)
Untitled-1.ipynb Cell 1 line 9
     [89](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W0sdW50aXRsZWQ%3D?line=88)     await server.stop()
     [91](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W0sdW50aXRsZWQ%3D?line=90) loop = asyncio.get_event_loop()
---> [92](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W0sdW50aXRsZWQ%3D?line=91) loop.run_until_complete(run(loop))

File [~/.conda/envs/env1/lib/python3.11/asyncio/base_events.py:629](https://file+.vscode-resource.vscode-cdn.net/home/ahmad/lab/Brain-Controller-App/~/.conda/envs/env1/lib/python3.11/asyncio/base_events.py:629), in BaseEventLoop.run_until_complete(self, future)
    618 """Run until the Future is done.
    619 
    620 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    626 Return the Future's result, or raise its exception.
    627 """
    628 self._check_closed()
--> 629 self._check_running()
    631 new_task = not futures.isfuture(future)
    632 future = tasks.ensure_future(future, loop=self)

File [~/.conda/envs/env1/lib/python3.11/asyncio/base_events.py:588](https://file+.vscode-resource.vscode-cdn.net/home/ahmad/lab/Brain-Controller-App/~/.conda/envs/env1/lib/python3.11/asyncio/base_events.py:588), in BaseEventLoop._check_running(self)
    586 def _check_running(self):
    587     if self.is_running():
--> 588         raise RuntimeError('This event loop is already running')
    589     if events._get_running_loop() is not None:
    590         raise RuntimeError(
    591             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running

```

**Comment by ahmad11111111111** [comment]
I got this error on the example

**Comment by ahmad11111111111** [comment]
i tested bluetooth and its running, but i dont know how bless interacts with bluetooth

**Comment by kevincar** [comment]
It is possible that bless won't run in a Jupyter note book because it runs asynchronously (see [this](https://stackoverflow.com/questions/47518874/how-do-i-run-python-asyncio-code-in-a-jupyter-notebook) if you really insist on using jupyter). You should simply call the script from your command line

> i tested bluetooth and its running, but i dont know how bless interacts with bluetooth

So you don't have any issues with the example script? You shouldn't need to worry about how bless interacts with bluetooth. Bless is the python library that provides bluetooth server functionality.

**Comment by ahmad11111111111** [comment]
``` (env1) ➜  examples git:(master) python gattserver.py 
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:__main__:51ff12bb-3ed8-46e5-b4f9-d64e2fec021b: Unknown
DEBUG:__main__:Advertising
INFO:__main__:Write '0xF' to the advertised characteristic: 51FF12BB-3ED8-46E5-B4F9-D64E2FEC021B
^CTraceback (most recent call last):
  File "/home/ahmad/lab/bless/examples/gattserver.py", line 94, in <module>
    loop.run_until_complete(run(loop))
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ahmad/lab/bless/examples/gattserver.py", line 80, in run
    trigger.wait()
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt

(env1) ➜  examples git:(master) python server.py    
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:__main__:51ff12bb-3ed8-46e5-b4f9-d64e2fec021b: Unknown
DEBUG:__main__:Advertising
INFO:__main__:Write '0xF' to the advertised characteristic: 51FF12BB-3ED8-46E5-B4F9-D64E2FEC021B
^CTraceback (most recent call last):
  File "/home/ahmad/lab/bless/examples/server.py", line 93, in <module>
    loop.run_until_complete(run(loop))
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/home/ahmad/.conda/envs/env1/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
```

**Comment by ahmad11111111111** [comment]
this is the output from the command line

**Comment by kevincar** [comment]
Which one is the error? The first error is a `KeyboardInterrupt` indicated you stoped it, the last error seems to be cut off.

**Comment by ahmad11111111111** [comment]
it was running continuously. i keyboard interrupted to stop the process

**Comment by ahmad11111111111** [comment]
this is the output before i interrupt it.

``` (env1) ➜  examples git:(master) python server.py
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:__main__:51ff12bb-3ed8-46e5-b4f9-d64e2fec021b: Unknown
DEBUG:__main__:Advertising
INFO:__main__:Write '0xF' to the advertised characteristic: 51FF12BB-3ED8-46E5-B4F9-D64E2FEC021B
```

**Comment by kevincar** [comment]
> it was running continuously. i keyboard interrupted to stop the process

Perfect! That means it's working. To gracefully shut it down you need to download either [LightBlue](https://punchthrough.com/lightblue/) (my personal favorite) or [nRF connect](https://www.nordicsemi.com/Products/Development-tools/nrf-connect-for-mobile). These apps allow you to programmatically test for Bluetooth. 

Using these apps you can select your program. The prompt in the program indicates that you should:

`Write '0xF' to the advertised characteristic: 51FF12BB-3ED8-46E5-B4F9-D64E2FEC021B`

This means it wants you to send the value `0xF` (Which the hexadecimal equivalent of 15) to the characteristic listed on the app with the indicated UUID.

This is all just to ensure that your reading/writing of bluetooth work as expected. 

For the `bci` program. bluetooth is only necessary for controlling the system using the companion mobile app. So all of this may be overkill if you plan to simply run it on your machine rather than directly on our subject's computer.

**Comment by ahmad11111111111** [comment]
yeah i think where in a good spot. ill try and see if i can do some testing back in Alabama this weekend.
